repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
-   repo: https://github.com/HE-Xinyu/pre-commit-android
    rev: 9b6a7fedcdd2bd106e41cec1fcdb717ae332fa84
    hooks:
    -   id: kotlin-formatter
